### PR TITLE
Update Semester Jul - Dec 2021.md

### PR DESCRIPTION
**Pull request by ajscheema**
ok

### CODE REVIEW

**Comment by ajscheema** [comment]
ok

**Comment by ajscheema** [comment]
[Semester Jul - Dec 2021.md](https://github.com/ritubits/TeachingOpenSourceSoftwareEngg/files/7446052/Semester.Jul.-.Dec.2021.md)

**Comment by ajscheema** [comment]
ok

**Comment by ajscheema** [comment]
[Semester Jul - Dec 2021.md](https://github.com/ritubits/TeachingOpenSourceSoftwareEngg/files/7446053/Semester.Jul.-.Dec.2021.md)

**Comment by ritubits** [comment]
Thanks

**Pull request merged**
